/* eslint-disable spellcheck/spell-checker */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    {
      type: "html",
      value: `<div class='sidebar_top_wrapper'>
                <div class='sidebar_top'>
                  <div class='sidebar_top_logo is-dark'>
                    <a target="_blank" rel="noopener noreferrer" href="/">
                      <img src="/logo/site-logos/marketing-dark.svg" alt='' />
                    </a>
                    <a href="/">
                      <img src="/logo/site-logos/docs-dark.svg" alt='' />
                    </a>
                  </div>
                  <div class='sidebar_top_logo is-light'>
                    <a target="_blank" rel="noopener noreferrer" href="/">
                      <img src="/logo/site-logos/marketing-light.svg" alt='' />
                    </a>
                    <a href="/">
                      <img src="/logo/site-logos/docs-light.svg" alt='' />
                    </a>
                  </div>
                </div>

                <div class='sidebar_bottom'>
                  <a target="_blank" rel="noopener noreferrer" href="https://www.permit.io/">
                    <div>
                      <img src="/sidebar-top-icons/normal-icons/marketing-home.svg" alt='' />
                      <img src="/sidebar-top-icons/hover-icons/marketing-home.svg" alt='' />
                    </div>
                    Permit Homepage
                  </a>
                  <a target="_blank" rel="noopener noreferrer" href="https://api.permit.io/v2/redoc">
                    <div>
                      <img src="/sidebar-top-icons/normal-icons/api.svg" alt='' />
                      <img src="/sidebar-top-icons/hover-icons/api.svg" alt='' />
                    </div>
                    API Reference
                  </a>
                  <a target="_blank" rel="noopener noreferrer" href="https://permit-io.slack.com/join/shared_invite/zt-nz6yjgnp-RlP9rtOPwO0n0aH_vLbmBQ#/shared-invite/email">
                    <div>
                      <img src="/sidebar-top-icons/normal-icons/slack.svg" alt='' />
                      <img src="/sidebar-top-icons/hover-icons/slack.svg" alt='' />
                    </div>
                    Slack Community
                  </a>
                  <a target="_blank" rel="noopener noreferrer" href="https://github.com/permitio">
                    <div>
                      <img src="/sidebar-top-icons/normal-icons/github.svg" alt='' />
                      <img src="/sidebar-top-icons/hover-icons/github.svg" alt='' />
                    </div>
                    GitHub
                  </a>
                </div>
              </div>`, // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: "doc",
      id: "quickstart",
    },
    {
      type: "category",
      label: "Start Quickly",
      className: "category-as-header",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Walkthroughs",
          items: ["overview/connecting-your-app"],
        },
        {
          type: "category",
          label: "Examples",
          link: {
            type: "generated-index",
            slug: "/category/learn-by-example",
            title: "Learn by Example",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "modeling",
            },
          ],
        },
        {
          type: "category",
          label: "Best Practices",
          items: ["how-to/ownership"],
        },
      ],
    },
    {
      type: "category",
      label: "Model Policies",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        {
          type: "category",
          label: "Roles (RBAC)",
          items: [
            {
              type: "autogenerated",
              dirName: "how-to/build-policies/rbac",
            },
          ],
        },
        {
          type: "category",
          label: "Attributes (ABAC)",
          items: [
            {
              type: "autogenerated",
              dirName: "how-to/build-policies/abac",
            },
          ],
        },
        {
          type: "category",
          label: "Relationships (ReBAC)",
          items: [
            {
              type: "autogenerated",
              dirName: "how-to/build-policies/rebac",
            },
          ],
        },
        {
          type: "category",
          label: "Policy as Code (PBAC)",
          link: {
            type: "doc",
            id: "integrations/gitops/custom_policy",
          },
          items: [
            "integrations/gitops/custom_policy",
            // "integrations/gitops/overview",
            "integrations/gitops/github",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Enforce Permissions",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        {
          type: "category",
          label: "The Policy Decision Point (PDP)",
          link: {
            type: "doc",
            id: "concepts/pdp/overview",
          },
          items: ["concepts/pdp/configuration"],
        },
        "how-to/enforce-permissions/check",
        "how-to/enforce-permissions/bulk-check",
        "how-to/enforce-permissions/data-filtering",
        {
          type: "category",
          label: "Permission Queries",
          items: [
            "how-to/enforce-permissions/list-role-assignments",
            "how-to/enforce-permissions/user-permissions",
            "how-to/enforce-permissions/all-tenants-check",
            "how-to/enforce-permissions/authorized-users",
          ],
        },
        { type: "doc", label: "Frontend", id: "integrations/feature-flagging/casl" },
      ],
    },
    {
      type: "category",
      label: "Work with Data",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        {
          type: "category",
          label: "Users and Identities",
          items: [
            "how-to/sync-users",
            {
              type: "doc",
              label: "JWTs",
              id: "authentication/your-authentication",
            },
            {
              type: "category",
              label: "SCIM",
              link: {
                type: "doc",
                id: "integrations/SCIM/SCIM overview",
              },
              items: [
                {
                  type: "doc",
                  id: "integrations/SCIM/OKTA",
                  label: "Okta SCIM Integration",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Custom Data",
          items: [
            "how-to/manage-data/loading-data",
            "how-to/manage-data/use-external-data-source",
            "how-to/manage-data/local-facts-uploader",
            "how-to/bulk-operations",
            "how-to/manage-data/pdp-sharding",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Manage SDLC",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        {
          type: "category",
          label: "Test & Monitor",
          items: [
            "how-to/SDLC/authz-testing",
            {
              type: "category",
              label: "Audit Logs",
              link: {
                type: "doc",
                id: "how-to/use-audit-logs/types-and-filtering",
              },
              items: ["how-to/use-audit-logs/debug-mode", "how-to/use-audit-logs/troubleshooting"],
            },
            "how-to/use-audit-logs/logs-forwarder",
            { type: "autogenerated", dirName: "how-to/use-audit-logs/errors" },
          ],
        },
        {
          type: "category",
          label: "Deploy",
          link: { type: "doc", id: "how-to/deploy/deploy-to-production" },
          items: [
            {
              type: "category",
              label: "Cloud Hosts",
              link: {
                type: "generated-index",
                slug: "/category/cloud-hosts",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "how-to/deploy/cloud-hosts",
                },
              ],
            },
            "how-to/deploy/overview",
            "how-to/deploy/on-prem",
            {
              type: "category",
              label: "Managed Frontend Deployment",
              items: [{ type: "autogenerated", dirName: "foaz" }],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Connect Your App",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      /*
      - Nodejs
          - Introduction (currently - quickstart)
          - Nextjs
          - SDK Reference - External Link
      - Python
          - Introduction (currently - quickstart)
          - FastAPI
          - SDK Reference - External Link
      - Golang
          - Introduction (currently - quickstart)
          - SDK Reference - External Link
      - .NET
          - Introduction (currently - quickstart)
          - SDK Reference - External Link
      - Ruby on Rails
          - Introduction (currently - quickstart)
          - SDK Reference - External Link
      - Java
          - Introduction (currently - quickstart)
          - SDK Reference - External Link
      - PHP (Beta)
      - RUST (Beta)
      - Erlang (Beta)
      - Kotlin (Beta)
      - Terraform
          - Introduction
      - Frontend
          - React
          - Angular
      - Proxies & API Gateways
          - AWS API Gateway
          - Kong
          - NGNIX
      - GraphQL
      */
      items: ["sdk/nodejs/quickstart-nodejs"],
    },
    {
      type: "category",
      label: "Integrate with Authentication",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        /**
         - Auth0
          - Introduction
      - Cognito
      - FusionAuth
      - SuperTokens
      - Hanko
         */
        "authentication/fusionauth",
      ],
    },
    {
      type: "category",
      label: "Embed Frontend Components",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      link: {
        type: "doc",
        id: "embeddable-uis/overview",
      },
      /*
      - User Management
      - Access Request
      - Audit Logs
      - Approval Flows
      - Guides (category)
      */
      items: ["embeddable-uis/element/user-management"],
    },
    {
      type: "category",
      label: "Advanced Learning",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: ["overview/glossary"],
    },
    {
      type: "category",
      label: "Updates and Feedback",
      collapsed: false,
      collapsible: false,
      className: "category-as-header",
      items: [
        "updates-and-feedback/changelog",
        "updates-and-feedback/roadmap",
        "updates-and-feedback/feature-requests",
        "faq",
        "status",
      ],
    },
  ],
};

module.exports = sidebars;
